### model
# If you have a local path, replace with your local checkpoint directory.
model_name_or_path: Qwen/Qwen3-VL-2B-Instruct
trust_remote_code: true
flash_attn: fa2


# Use a writable Hugging Face cache directory (avoids permission issues if ~/.cache/huggingface is root-owned).
cache_dir: /home/work/byounggun/.cache/hf

# Qwen3-VL processor settings (keep consistent with Qwen examples)
# image_max_pixels: 262144
image_max_pixels: 65536
# video_max_pixels: 16384

# Add our new special token used in targets
# LLaMAFactory will automatically switch resize_vocab to true when new tokens are added.
add_special_tokens: "<trajectory>"

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_rank: 32
lora_target: all
pref_beta: 0.05
pref_loss: orpo  # choices: [sigmoid (dpo), orpo, simpo]

### dataset
# Uses ORPO/DPO-style ranking format written by scripts/orad3d_build_vlm_orpo_v2.py (--orpo)
# dataset_info.json must exist under dataset_dir.
dataset: orad3d_orpo3

# Point this to the folder that contains both:
#   - dataset_info.json
#   - your generated *_training_orpo.jsonl
dataset_dir: ./data
media_dir: /home/work/datasets/bg/ORAD-3D

# Qwen3-VL template; nothink is usually preferred for SFT
template: qwen3_vl_nothink
cutoff_len: 12288
preprocessing_num_workers: 8   # tokenizer / map 단계
dataloader_num_workers: 8     # 학습 중 batch 공급

### output
output_dir: /home/work/datasets/bg/byounggun/saves/orad3d/qwen3-vl-2b/lora/orpo3
logging_steps: 10
save_strategy: epoch
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
disable_gradient_checkpointing: true

per_device_train_batch_size: 8
gradient_accumulation_steps: 2
learning_rate: 1.0e-4
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true

ddp_timeout: 180000000
resume_from_checkpoint: null
