### model
# If you have a local path, replace with your local checkpoint directory.
model_name_or_path: Qwen/Qwen3-VL-2B-Instruct
trust_remote_code: true
flash_attn: fa2


# Use a writable Hugging Face cache directory.
cache_dir: /home/work/byounggun/.cache/hf

# Qwen3-VL processor settings (keep consistent with Qwen examples)
# image_max_pixels: 262144
image_max_pixels: 65536
# video_max_pixels: 16384

# Add our new special token used in targets
# LLaMAFactory will automatically switch resize_vocab to true when new tokens are added.
add_special_tokens: "<trajectory>"

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 32
lora_target: all

### dataset
# Uses ShareGPT multimodal format written by scripts/orad3d_build_vlm_sharegpt.py
# dataset_info.json must exist under dataset_dir.
dataset: orad3d_vlm_refine

# Use the repo dataset registry (data/dataset_info.json). The dataset file itself can live elsewhere.
dataset_dir: ./data
media_dir: /home/work/datasets/bg/ORAD-3D

# Qwen3-VL template; nothink is usually preferred for SFT
template: qwen3_vl_nothink
cutoff_len: 4096
preprocessing_num_workers: 8   # tokenizer / map 단계
dataloader_num_workers: 8     # 학습 중 batch 공급

### output
output_dir: /home/work/datasets/bg/byounggun/saves/orad3d/qwen3-vl-2b/lora/sft_v2_refine
logging_steps: 10
save_strategy: epoch
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
disable_gradient_checkpointing: true

per_device_train_batch_size: 8
gradient_accumulation_steps: 2
learning_rate: 1.0e-4
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true

ddp_timeout: 180000000
resume_from_checkpoint: null
